// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wabzpbpgdkdudvdpfgjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhYnpwYnBnZGtkdWR2ZHBmZ2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NjU3NTIsImV4cCI6MjA2NTE0MTc1Mn0.mh_0fw5zC0stD1VmtiIiQqttCEt0de-DYW6ImHgW-BA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);